.TH PGROLECHECK 1
.SH NAME
pgrolecheck \- Check the roles of PostgreSQL servers.
.SH SYNOPSIS
.B pgrolecheck
.RI [ options ]
.SH DESCRIPTION
pgrolecheck is a tool to check whether PostgreSQL servers are running as primary servers or standby replicas. It provides a web interface accessible over HTTP(S), offering a simple HTTP GET endpoint that returns the current roles of the PostgreSQL servers in JSON or CSV format.
.SH OPTIONS
.TP
.B \-\-config
Specify the path to the configuration file. Default is /etc/pgrolecheck/pgrolecheck.conf.
.TP
.B \-\-dbconfig
Specify database configuration as a JSON string. Can be used multiple times for multiple databases. Example: \-\-dbconfig '{"Name":"db1","DbName":"postgres","User":"user","Password":"password","Host":"localhost","Port":"5432","SslMode":"disable"}'
.TP
.B \-\-listenip
The IP address the web server listens on. Use "*" or "0.0.0.0" to listen on all available IPs.
.TP
.B \-\-httpport
The port number for HTTP(S) connections.
.TP
.B \-\-usessl
Enable SSL for the webserver. Specify "true" to enable.
.TP
.B \-\-certfile
Path to the SSL certificate file.
.TP
.B \-\-keyfile
Path to the SSL private key file.
.TP
.B \-\-logfile
Path to the log file. Set to "syslog" to use the system logger, or specify a file path.
.TP
.B \-\-outputformat
Specifies the output format of the web service. Options are "json" (default) and "csv".
.TP
.B \-f
Run in foreground and log to STDOUT.
.SH CONFIGURATION FILE
The configuration file for pgrolecheck is located at
.B /etc/pgrolecheck/pgrolecheck.conf
. This file controls various aspects of pgrolecheck's behavior and can be overridden by command-line options.
.PP
The configuration file consists of several sections with specific parameters:
.RS
.TP
.B [database_db1], [database_db2], ...
Specifies the database connection parameters for multiple databases. Repeat the section with unique names for each database.
.RS
.TP
.B dbname
Name of the database to connect to. Essential for establishing the database connection.
.TP
.B user
Database user for authentication. Required for accessing the database.
.TP
.B password
Password for the specified database user. Ensure this is kept secure.
.TP
.B host
Hostname or directory of the database server. Use a directory path for Unix domain socket connections or a hostname/IP for TCP/IP connections.
.TP
.B port
Database server port. Essential for TCP/IP connections. For Unix domain sockets, this can be left empty or set to the default port (5432).
.TP
.B sslmode
Determines SSL usage for the connection. Options: disable, require, verify-ca, verify-full. "disable" is common for local connections.
.RE
.TP
.B [server]
Specifies the web server parameters for handling HTTP requests.
.RS
.TP
.B listen_ip
IP address to bind the web server. "*" or "0.0.0.0" listens on all interfaces, whereas specifying an IP restricts it to that IP.
.TP
.B use_ssl
Enable SSL for the web server.
.TP
.B http_port
Port number on which the server accepts HTTP(S) connections. Ensure this port is open in the firewall.
.TP
.B cert_file
Path to the SSL certificate file for HTTPS. Required for establishing secure connections.
.TP
.B key_file
Path to the SSL private key file. Must correspond to the certificate file for successful SSL encryption.
.TP
.B output_format
Specifies the output format for the web service. Default is "json". Options: "json", "csv".
.RE
.TP
.B [logging]
Defines how pgrolecheck logs its operations.
.RS
.TP
.B log_file
Path to where logs are written. Setting this to "syslog" uses the system logger. Otherwise, specify a filesystem path for logging to a file. Ensure the application has write permissions to the file or directory.
.RE
.SH FILES
.TP
.B /etc/pgrolecheck/pgrolecheck.conf
The main configuration file.
.SH SEE ALSO
.BR postgresql (1),
.BR systemctl (1),
.BR journalctl (1)
.SH AUTHOR
pgrolecheck was written by Jonathan Petersson.
